# SQL Script to Retrieve COMPAS Data {#appendix-c}

\noindent I wrote the following SQL script to retrieve the COMPAS data set used in Chapters \@ref(chap-3) and \@ref(chap-4) from the public COMPAS database available through the ProPublica Data Store [@compasdata] and accessible through GitHub (https://github.com/dashaasienga/Statistics-Senior-Honors-Thesis/tree/main/Data%20Sets/COMPAS), along with instructions for accessing the database and running this code. The database contains seven tables, although the `summary` table is empty. The SQL code was run on DB Browser for SQLite, and returns 12160 rows of defendants from Broward County, Florida, who were assessed using the COMPAS tool for risk of recidivating. There are 29 variables of interest returned, though many more could be selected if interested. Further data wrangling and data analysis are conducted in R, and selected findings are communicated in Chapters \@ref(chap-3) and \@ref(chap-4). Having uploaded `compas.db` into DB Browser for SQLite, execute the following code:  

```{eval = FALSE}
select 

# select variables of interest 
people.id,
compas.compas_person_id,
people.name,
people.first,
people.last,
people.sex,
people.race, 
people.age,
people.age_cat,
compas.marital_status,
compas.custody_status,
people.juv_fel_count,
people.juv_misd_count,
people.juv_other_count,
people.priors_count,
people.days_b_screening_arrest,
people.c_days_from_compas,
people.c_charge_degree,
people.c_charge_desc,
compas.type_of_assessment,
compas.raw_score,
people.decile_score,
compas.score_text,
people.is_violent_recid,
people.num_vr_cases,
people.is_recid,
people.num_r_cases,
round(jail_agg.days_in_jail) as days_in_jail,
round(prison_agg.days_in_prison) as days_in_prison

from compas

# join the 'people' table
inner join people
on compas.person_id = people.id
and compas.first = people.first
and compas.last = people.last
and compas.decile_score = people.decile_score

# join jail history for each defendant
left join  (

select 

jailhistory.person_id,
jailhistory.first,
jailhistory.last,
jailhistory.out_custody,
jailhistory.in_custody,
sum(
  distinct(
    julianday(
      jailhistory.out_custody
      ) - julianday(
        jailhistory.in_custody
        )
    )
  ) as days_in_jail

from jailhistory
	
inner join compas 
on compas.person_id = jailhistory.person_id
and compas.first = jailhistory.first
and compas.last = jailhistory.last
and jailhistory.in_custody <= compas.screening_date
	
group by jailhistory.person_id, jailhistory.first, jailhistory.last
	
) as jail_agg 
on jail_agg.person_id = people.id
and jail_agg.first = people.first
and jail_agg.last = people.last

# join prison history for each defendant
left join  (

select 

prisonhistory.person_id,
prisonhistory.first,
prisonhistory.last,
prisonhistory.out_custody,
prisonhistory.in_custody,
sum(
  distinct(
    julianday(
      prisonhistory.out_custody
      ) - julianday(
        prisonhistory.in_custody
        )
    )
  ) as days_in_prison

from prisonhistory
	
inner join compas 
on compas.person_id = prisonhistory.person_id
and compas.first = prisonhistory.first
and compas.last = prisonhistory.last
and prisonhistory.in_custody <= compas.screening_date
	
group by prisonhistory.person_id, prisonhistory.first, prisonhistory.last
	
) as prison_agg 
on prison_agg.person_id = people.id
and prison_agg.first = people.first
and prison_agg.last = people.last

# filter only for risk of recidivism
where type_of_assessment = 'Risk of Recidivism'
```

