# Corrections {-}

When originally submitted, this honors thesis contained some errors which have been corrected in the current version. Here is a list of the errors that were corrected.

- Page 4: Changed "minimize average error, which fits majority populations" to "minimize average error over the entire data set, which tends to result in fits to majority populations".

- Page 10: Italicized 'Independence' and 'Separation' to convey their meanings specifically as notions of fairness. 

- Page 11: Changed "had recidivated when they hadn't" to "would recidivate when they had not" and "had not recommitted" to "would not recommit".

- Page 13: Italicized 'sufficiency' to convey its meaning specifically as notions of fairness. 

- Page 13: Changed 'people' to 'individuals'.

- Page 13: Changed 'definitions' to 'fairness definitions'. 

- Page 14: Changed 'notion' to 'notation'.

- Page 14: Changed 'GPAs' to 'GPA distributions'.

- Page 16: Changed "this equation" to "Equation 1.18".

- Page 16: Changed "However, its direct implication is" to "The direct implication of Equation 1.18 is".

- Page 19: Changed 'certain' to 'these'. 

- Page 20: Changed 'regression to 'simple linear regression'.

- Page 23: Changed 'parameter' to 'tuning parameter'.

- Page 27: Changed 'algorithm' to 'ML algorithm'.

- Page 27: Changed 'Seldonian algorithms' to 'the Seldonian framework'.

- Page 28: Changed 'algorithm' to 'ML algorithm'.

- Page 40: Changed 'had recommitted' to 'recommitted'. 

- Page 40: Added "on this final data set" to the end of the second paragraph of Section 3.1.

- Page 58: Removed '$\textit{; } \delta = 0.05$' from Equation 3.4 as $\delta$ is defined in the following line.

- Page 68, 74: Replaced three commas with the conjunction 'and'.

In addition to the above corrections, the notation for an algorithm was changed from $a \in \textbf{A}$ to $\textbf{a} \in \textbf{A}$ in approximately 7 places to avoid confusion with the notation for demographic groups $a, b \in A$. Finally, 3 spelling corrections were made in the thesis. 



